sudo: required
services:
  - docker

before_install:
  - docker build -t pavlochigishev/qa.coach-test-www:latest -f ./www/Dockerfile.dev ./www

scripts:
  # unit tests and linting here
  - docker run -e CI=true pavlochigishev/qa.coach-test-www:latest yarn run test

after_success:
  - docker build -t pavlochigishev/qa.coach-prod-web:latest ./www
  - docker build -t pavlochigishev/qa.coach-prod-api-server:latest ./api-server
  - docker build -t pavlochigishev/qa.coach-prod-worker:latest ./worker
  - docker build -t pavlochigishev/qa.coach-prod-nginx:latest ./nginx
  # docker login via CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push built images to docker hub
  - docker push -a pavlochigishev/qa.coach-prod-web
  - docker push -a pavlochigishev/qa.coach-prod-api-server
  - docker push -a pavlochigishev/qa.coach-prod-worker
  - docker push -a pavlochigishev/qa.coach-prod-nginx

